CREATE TABLE IF NOT EXISTS local_users
    (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash INTEGER NOT NULL)

CREATE TABLE IF NOT EXISTS registered_users
    (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash INTEGER NOT NULL)