CREATE TABLE IF NOT EXISTS users(

    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE COLLATE NOCASE,
    email TEXT NOT NULL COLLATE NOCASE,
    password_hash INTEGER NOT NULL
    )